version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.38.0
    container_name: hasura
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:password@postgres:5432/mydb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: mysecret
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/mydb
    ports:
      - "4000:4000"

  strapi:
    build: ./strapi
    container_name: strapi
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: mydb
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: password
    ports:
      - "1337:1337"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
      - hasura
    environment:
      NEXT_PUBLIC_HASURA_URL: http://localhost:8080/v1/graphql
      NEXT_PUBLIC_BACKEND_URL: http://localhost:4000
    ports:
      - "3000:3000"

volumes:
  pg_data:
